name: Build and Deploy
on:
  push:
    branches:
      - main

permissions:
      contents: read
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

# concurrency: ci-${{ github.ref }}

    # Deploy to the github-pages environment
jobs:
  deploy:
    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Deploy 
        # uses: layanb4/github-pages-deploy-action@v4
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
        with:
          branch: gh-pages # The branch the action should deploy to.
          repositorty-name: layanb4/GitHubPagesDeployment
          target-folder: public
        
      
